### ISSUE TITLE
`migrate_7x_claw` barfs when AUDIT datastream is missing

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#1004]
We need to do some null checks around the audit file migration, otherwise this one will stop the whole show.

Pretty sure this is what you experiencing @rosiel.

**Comment by rosiel** [comment]
Success - it didn't blow up! 

```
 [notice] Processed 21 items (6 created, 0 updated, 0 failed, 15 ignored) - done with 'islandora_audit_file'
```

The 14 messages that were generated were "missing Audit datastream" for 14 of the batch of 22 that i (just before this) batch loaded. Indeed they don't have audit ds's (i exported foxml from Fedora). So... that's odd, right? This is a total sidenote because this has nothing to do with the migration, but it would seem in 7.x, creating objects with Batch can leave you with some (again: but not all) objects with no AUDIT.
