### ISSUE TITLE
How do I use Context to persist thumbnail files in Fedora?

### ISSUE THREAD

**Issue by mjordan** [Islandora-CLAW/CLAW#1037]
I've created a Context that indexes a file in Gemini if its Media has the "Thumbnail Image" tag:

![image](https://user-images.githubusercontent.com/403918/53541293-fbe05300-3acd-11e9-94ac-8bcfacaf200e.png)

I can see the thumbnail file's resource in Fedora (and Gemini) but I can see no evidence that the binary file itself has been persisted to Fedora. How can I use Context to persist the thumbnail binary file to Fedora? There is nothing but a 404 at http://localhost:8080/fcrepo/rest/2019-02/7-Thumbnail%20Image.jpg, for example.

**Comment by seth-shaw-unlv** [comment]
You don't need to create a new context to get Thumbnails in Fedora+Gemini.

To update where generated thumbnails are stored (Fedora v. Drupal) update the "Image - Generate a thumbnail from a service file" Action (`/admin/config/system/actions/configure/generate_a_thumbnail_from_an_image_service_file`). Scroll down to the "File system" dropdown and select "fedora" and Save the configuration.
<img width="921" alt="screen shot 2019-02-28 at 10 27 25 am" src="https://user-images.githubusercontent.com/29869988/53589338-fc1b3580-3b43-11e9-80e1-be5c9da36818.png">
After that new thumbnails will be saved to Fedora (and will be covered with the existing contexts, resulting in Gemini indexing) instead of the Drupal public filesystem. 

You can configure Service files to be stored in Fedora by updating it's corresponding action in the same way.

There is no easy way I'm aware of to move a file between filesystems once it has been created, though.

**Comment by seth-shaw-unlv** [comment]
Addendum, yeah, I'm not seeing anything for moving files from one filesystem to the other that would apply in our case. 

One option is to create a migration using the existing files and media as the source and new files and media entities using the fedora file system, but then you would still need to clean up the original ones once you are done.

Another option is to code a new action that will copy the file from public to fedora, update the media file reference, delete the original file, and then trigger the indexing actions. You would then have to use something like views_bulk_operations to trigger the action on the media/files in question.

**Comment by mjordan** [comment]
@seth-shaw-unlv super, that worked. I agree there's the question of retroactively changing the destination of a file. Maybe we should open a separate issue for that?

**Comment by mjordan** [comment]
OK to close this since it's documented in the flysystem technical docs?

**Comment by seth-shaw-unlv** [comment]
Fine by me.
