### ISSUE TITLE
How to best map RDF to fields?

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#342]
Should we use the RDF api, which is sadly still hook based?  Do we consider using a UI?  What are peoples thoughts about [RDF UI](https://www.drupal.org/project/rdfui)?  Should we use it?  Extend it?  Throw it out and do something ourselves?

If we want a UI, consider wireframe diagrams and workflows.

**Comment by DiegoPino** [comment]
RDF UI uses RDF api(first depends on the later) and right now is based on schema.org types and predicates. RDF api is hook-based because it was faster to port but also because RDF in drupal is really a presentation layer stuff(rdfa). But, everything here depends really on easyrdf which is core so our choices are really ample.

**Comment by dannylamb** [comment]
Closing since sprint is over.  We can open another ticket to 'revisit' this concept later if required.
