### ISSUE TITLE
Remove ldp:contains from FedoraResource entity

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#397]
Using inverses, like hasParent instead of ldp:contains, makes views easier and is generally better for performance.

Get rid of [this](https://github.com/Islandora-CLAW/islandora/blob/3158fc97aa9e333ebd85632c767b37897793d397/src/Entity/FedoraResource.php#L323-L346).

**Comment by DiegoPino** [comment]
@dannylamb as discussed, before making this absolute, lets try and test in terms of UI and inline entity form editing. Mostly because LDP works from trunk to leaves making an  acyclic graph == tree, same way as you would expect editing from a human perspective would be: "i go to the main pcdm:Object and edit/change there the child binaries, etc." By using inverses to link our drupal resources editing would end being also the other way.

**Comment by dannylamb** [comment]
Making new ticket, then.

**Comment by dannylamb** [comment]
Re-opening.  NonRDFResources do not ldp:Contain anything.  It should at least be removed as a base field.

**Comment by whikloj** [comment]
PR - https://github.com/Islandora-CLAW/islandora/pull/26
