### ISSUE TITLE
Create a ContextGenerator service

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#493]
We need a service that will receive a RdfMapping configuration entity and return a jsonld context.  The context should be taken to as much detail as possible, up to the point of removing namespaces, if possible.

The interface would be
```php
public function generateContext(RdfMapping $mapping);
``` 

It should just return the context as a string.  Persisting/caching the context is a separate issue.

Be sure to update islandora.services.yml.

**Comment by ajs6f** [comment]
If RdfMapping contains essentially the same info as a JSON-LD context, would it be possible to actually use JSON-LD contexts as the mappings instead of having a new construct? (Just thinking out loud here, making sure I understand the problem.)

**Comment by ajs6f** [comment]
I'm assuming that there is some kind of appropriate such type in Drupal-land.

**Comment by DiegoPino** [comment]
@ajs6f I get you. JSON-LD context could be perfectly seen as the mapping, would depend on how are we constructing the JSON-LD context and how clever the mechanism is there to remove all not used(but declared namespaces) per bundle.

@daniel-dgi would this the opposite - revert- of this but exposed as a service? 
https://github.com/Islandora-CLAW/claw-jsonld/commit/4168e9fb2d23542edc6527e1852d839dc3c82234

Means reintroducing the removed context and making it a separate service would do it?

**Comment by dannylamb** [comment]
@DiegoPino I'm really just trying to separate the generating of jsonld from the generating of the context, and also (later) the storage/retrieval of the context and its usage.  

This will re-introduce the creation of the context, but not every time an object is serialized as before Islandora-CLAW/claw-jsonld#1.  I plan on generating a context in response to write operations on rdf mappings and caching the results.

**Comment by DiegoPino** [comment]
@dannylamb cool, thanks.

**Comment by dannylamb** [comment]
@ajs6f The RdfMapping configuration entity is core Drupal, used to put RDFa output in the html.  It carries all the same information we need for both this and #491.

They're configuration entities, which are queryable (to an extent) and yml serializable. @DiegoPino and I have been involved in discussions around a UI for manipulating these, since the one provided by the Drupal community is hard-wired for schema.org only.

**Comment by ajs6f** [comment]
Holy moly yes, from the SI POV the ability to deal with stuff other than schema.org is imperative. Mappings, yes, but also _framing_!

**Comment by DiegoPino** [comment]
This will take me some days(like 5?). But I assigned it to myself and added a physical reminder to myself to be able to accomplish a working prototype on time. Will have probably a LOT of questions.

**Comment by DiegoPino** [comment]
@dannylamb @whikloj i have a working "thing" for this now that should do the Job. 
I hope my `@context` key naming -URI compacting- algorithm makes sense.
Will pull tonight kinda late (sorry) since today is office-away-diego-on-subway day and will be moving a lot. Will keep you updated. 
By the way, the JSON-LD compaction from Fedora 4.71. you shared @whikloj yesterday is broken, which leads to a lot of other talks related to this.

**Comment by dannylamb** [comment]
@DiegoPino Great, just issue a PR when you feel it is ready.

Perhaps it would be good to report the compaction behaviour to @awoods?

**Comment by DiegoPino** [comment]
@dannylamb
> compaction behaviour to @awoods?
true. Will need a bit more background from @whikloj (ping, ping) to be able to replicate and report as 🐛 

Thanks!

**Comment by awoods** [comment]
I saw @whikloj's comment in the following ticket:
https://jira.duraspace.org/browse/FCREPO-2243
..but according to @acoburn, there is no actual issue/bug. 

What problem are you seeing @DiegoPino ?

**Comment by DiegoPino** [comment]
@awoods sorry,  was away the whole day and catching up. 
Seems to be a series of version changes, misunderstandings, internal communications and some minor issues regarding flattening in compacted form versus expanded. 
Mostly on my perception that later form, according to my interpretation of [API algorithm pseudo code](http://www.w3.org/TR/json-ld-api/#flattening-algorithms), seemed to be probably the most natural if we are not being explicit about compaction.

And  a little on URI expansion algorithm that leads to stuff like
````
"xsi":"xs:-instance",
"xs":"http://www.w3.org/2001/XMLSchema",
````

which in my humble opinion seemed strange, since `http://www.w3.org/2001/XMLSchema` and `http://www.w3.org/2001/XMLSchema-instance`
are different URLs/URI, so that type of URI compactions seemed to my eyes wrong. But as most of the time I can, and probably am, wrong.

I wrote a manuscript! [here](https://gist.github.com/whikloj/914aaff77758c5817fbe0b031a5e2c78#gistcomment-1980844) for @acoburn since I really really had no intention making such a fuss about this.

thanks!

**Comment by acoburn** [comment]
@DiegoPino just in case you're not getting tagged on my response, here it is: https://gist.github.com/whikloj/914aaff77758c5817fbe0b031a5e2c78#gistcomment-1980857

**Comment by DiegoPino** [comment]
@acoburn indeed. Gist was not tagging me, thanks! will answer there but for now, thanks again 👍

**Comment by acoburn** [comment]
@DiegoPino IMO, a user should have complete control over namespace definitions, which is why I wrote this: https://github.com/acoburn/trellis-namespaces -- it completely separates the notion of namespaces from the notion of a repository's persistence layer.
