### ISSUE TITLE
Install and enable Carapace theme

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#700]
Add https://github.com/Islandora-CLAW/carapace to the list of modules to be installed in Drupal: https://github.com/Islandora-Devops/claw-playbook/blob/master/inventory/vagrant/group_vars/webserver/drupal.yml#L19

**Comment by jonathangreen** [comment]
My vote is that it is pulled in through composer.

**Comment by dannylamb** [comment]
@jonathangreen I agree, but we need to sort out how that will happen.  If the drupal role we're using doesn't support it, then we'll need to implement it ourselves.

**Comment by DiegoPino** [comment]
@dannylamb @jonathangreen there will be moments and places where we will be still be using ```drush```. Not everything can come via composer, probably the theme itself can, and some dependencies). Enabling of and setting as default(e.g ```drush config-set system.theme default carapace```)

**Comment by dannylamb** [comment]
@DiegoPino Yeah, for sure.  Composer is just for pulling down code with its dependencies.

**Comment by bryjbrown** [comment]
@dannylamb To be installed via composer, does carapace have to be on packagist.org, or can composer install it from GitHub?

**Comment by dannylamb** [comment]
@bryjbrown Either, though in practice we've found putting it up on packagist to be easier.  Just using Github then spams their API, and you have to pass in an extra authentication key to prevent from getting throttled.

**Comment by dannylamb** [comment]
@jonathangreen Upon inspection it looks like the drupal role is geared towards building from a composer project, so looks like we add it to https://github.com/Islandora-CLAW/drupal-project to get the code pulled down and also add it to https://github.com/Islandora-Devops/claw-playbook/blob/master/inventory/vagrant/group_vars/webserver/drupal.yml#L19 to get it enabled.

I'm not sure what we'd need to do to set it to default, or if that's even required.  But those two things would be a good start once carapace is on packagist.

**Comment by jonathangreen** [comment]
@dannylamb does it make sense to add it to drupal-project? We probably don't want to require that theme in order to use drupal project do we? 

Depending on the answer to that question we could add an additional variable to the `webserver-app` role with packages to have composer install... I don't think that would be too hard, and would be a potentially useful variable to have. The biggest thing would be doing the work to make sure its idempotent.

**Comment by DiegoPino** [comment]
@jonathangreen are you thinking about adding those with specific versions or just the package name?

**Comment by jonathangreen** [comment]
@DiegoPino either really 😄. I think behind the scenes it would be two composer calls, one to see if the package is already installed and another to install it if not. Instead of the first one call maybe we could look at the `composer.json` within Ansible. Have to see if anyone else is doing something like that, or if there is an easier way. 

If we are just passing the variable off to composer we can probably allow version numbers with the package name, the same way composer does. That would let us not specify version numbers for now, but specify them later when we want to. 

This may be all overthinking, and we should just add everything to `drupal-project`, I'm not sure. Thoughts?

**Comment by DiegoPino** [comment]
@jonathangreen i like 2x calls approach. Like a composer info and then the actual require call. 👍

**Comment by dannylamb** [comment]
@jonathangreen @DiegoPino Iterating over a list of them and composer requiring sounds good to me.  It'd be nice to have the flexibility in the playbook instead of a composer file.

**Comment by dannylamb** [comment]
Looks like this _should_ work with a `composer info` as @DiegoPino suggested.  I'll see what I can do with #671.

Will probably be bugging @jonathangreen about it.

**Comment by dannylamb** [comment]
Going to address the composer install under this issue instead of #671

**Comment by dannylamb** [comment]
Looks like this can be done automagically by the drupal role by defining `drupal_composer_dependencies` in https://github.com/Islandora-Devops/claw-playbook/blob/master/inventory/vagrant/group_vars/webserver/drupal.yml

I'm testing this out now.

**Comment by jonathangreen** [comment]
Do we want to jam the variables to set the theme to carapace in here somewhere? Or maybe we could make another ticket for that.

**Comment by dannylamb** [comment]
@jonathangreen You mean scrape the block's yml out of git and load it into Drupal?  Should be straightforward to do that a la https://github.com/Islandora-Devops/claw-playbook/blob/master/roles/internal/webserver-app/tasks/jwt.yml#L25-L40

If you don't run into any other issues bringing up the box, I can try my hand at that.

**Comment by jonathangreen** [comment]
Theme looks good to me, everything came up clean! 

It was really more of a question, we probably want the block to be placed when you spin up the vagrant box, so we need a way to do it. I think what your suggesting makes sense.

**Comment by jonathangreen** [comment]
Want me to merge PR and we can deal with setting the block in another ticket? Or do you want to give it a go here?

**Comment by dannylamb** [comment]
@jonathangreen Go ahead and merge and I'll set up another issue.

**Comment by dannylamb** [comment]
@jonathangreen https://github.com/Islandora-CLAW/CLAW/issues/706

**Comment by jonathangreen** [comment]
Closed with: 
https://github.com/Islandora-CLAW/CLAW/issues/671
