### ISSUE TITLE
dcterms vs dc11

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-CLAW/CLAW#803]
Fedora has the following pre defined namespace: `PREFIX dcterms: <http://purl.org/dc/terms/>`, which seems to be different from the dc11 defined here: https://github.com/Islandora-CLAW/islandora/blob/8.x-1.x/islandora.module#L72.  Are they two different ontologies?

In Fedora (http://future.islandora.ca:8080/fcrepo/rest/), the dc prefix is mapped to `http://purl.org/dc/elements/1.1/`.  

It seems like there is mismatch between how drupal is configured vs how [Fedora is configured](https://github.com/Islandora-CLAW/CLAW/commit/75c63653d4c20e41101067488919dff73d0fd4d7).

**Comment by dannylamb** [comment]
Yes, they are different ontologies.  `dcterms` extends `dc11`, adding extra predicates.  You also "should" use things not strings with dcterms.  So there's objects for agents, titles, coverages, etc...  `dc11` in theory is less restrictive since it lets you jam in strings if you don't have another resource to point to with a URL. It all depends on how far you're willing to go for "compliance" with an ontology.

This is my basic understanding of it.   @rosiel would know more.

And yes... the problem is that Drupal hardwires dcterms to use `dc` as a namespace prefix.  So we could edit the .cnd file to line up, but that may confuse people.  I'm :+1: to doing that, but others have expressed concern because traditionally it's been `dc` for 1.1 and `dcterms` for terms.

**Comment by rosiel** [comment]
Yep, what @dannylamb said! With a small correction regarding titles. The dc11 predicates don't have ranges, and the dcterms predicates sometimes do. Generally they lean to 'things not strings'.  Agents, subjects, even formats are now things-not-strings.  But `dcterms:title` has range Literal, so dcterms titles are an exception: strings-not-things.

 The namespace shorthand `dc` is often ambiguous, which is why _I_ prefer to use `dcterms` and `dc11`. If you read through http://dublincore.org/documents/dcmi-terms/ it helps to contextualize how they both exist together (i.e. there are two `title` properties in different namespaces, one with a range, and one without), and what the defined Classes are. 

A historical note - you may run across old (>10years) literature that mentions "Qualified Dublin Core". That was an attempt to make some of the original 15 predicates more granular or typed, but it is obsolete and has been superseded by dcterms.

**Comment by Natkeeran** [comment]
Thank you for the feedback.
