### ISSUE TITLE
Open Seadragon viewer fails for Anonymous user

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora-CLAW/CLAW#864]
Just did a stock build. Created a repository item with the tags "Image" and "Open Seadragon" with a Tiff File Media tagged "Preservation Master".

While viewing the item while logged in as admin the viewer works fine:
![screen shot 2018-06-29 at 9 14 02 am](https://user-images.githubusercontent.com/29869988/42103158-19dda440-7b7d-11e8-8464-430cfa3b9de9.png)

When I log out it only displays a blank viewer:
![screen shot 2018-06-29 at 9 14 33 am](https://user-images.githubusercontent.com/29869988/42103179-272afc7e-7b7d-11e8-9a52-12a48c7459c0.png)

It doesn't appear to be a permissions issue because I can download the tiff file. It isn't Cantaloupe because manual IIIF calls work, too. 

The Javascript console, when logged out, is reporting: 
```
js_0VW5a4AccOGefIc_97roTc7Fg2XqmgJAXaFh2s9hMEU.js:formatted:4290 Uncaught TypeError: $(...).once is not a function
    at Object.attach (js_Gn9pnRUoaNquy92_scmpSAUb_r6CrWRxniZ4RWBFAjk.js:27)
    at js_0VW5a4AccOGefIc_97roTc7Fg2XqmgJAXaFh2s9hMEU.js:formatted:4303
    at Array.forEach (<anonymous>)
    at Object.Drupal.attachBehaviors (js_0VW5a4AccOGefIc_97roTc7Fg2XqmgJAXaFh2s9hMEU.js:formatted:4300)
    at js_0VW5a4AccOGefIc_97roTc7Fg2XqmgJAXaFh2s9hMEU.js:formatted:4499
    at HTMLDocument.t (js_0VW5a4AccOGefIc_97roTc7Fg2XqmgJAXaFh2s9hMEU.js:formatted:12)
```

I've dabbled in JavaScript before, but this is beyond me.

**Comment by DiegoPino** [comment]
@seth-shaw-unlv maybe the issue is the .library.yml file.

Logged in users have jQuery loaded by default  (menu bars et all require that) so you never see the issue. But as anonymous, the library dependencies need to be specified correctly and the library needs to be attached too the page too of course. 

To find the real culprit r i would start by disabling "Aggregate JavaScript files" from config/performance settings form. Once the JS file that is really triggering the issue is detected, i would recheck

https://www.drupal.org/docs/8/creating-custom-modules/adding-stylesheets-css-and-javascript-js-to-a-drupal-8-module

v/s
https://github.com/Islandora-CLAW/openseadragon/blob/8.x-1.x/openseadragon.libraries.yml#L1

Like ours start with an `init:` and not the library name, which seems out of place to me, but maybe right (Duno)? I would start testing that file first to make sure it conforms to the D8 docs.

**Comment by seth-shaw-unlv** [comment]
Ah, thanks for the lead.

It looks like [the jquery-once dependency](https://github.com/Islandora-CLAW/openseadragon/blob/8.x-1.x/openseadragon.libraries.yml#L10) isn't listed correctly.  I checked [core.libraries.yml](http://cgit.drupalcode.org/drupal/tree/core/core.libraries.yml) and found that it should be 'core/jquery.once' instead of 'core/jquery-once'.

Indeed, fixing that works. PR shortly.

**Comment by seth-shaw-unlv** [comment]
Resolved by the linked PR.
