### ISSUE TITLE
Create default metadata profile

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#896]
See https://docs.google.com/spreadsheets/d/18u2qFJ014IIxlVpM3JXfDEFccwBZcoFsjbBGpvL0jJI/edit#gid=0

The 'Repository Item' content type is pretty bare bones.  Let's add to it using the spreadsheet above as guidance.  This means adding fields for what's listed (either as strings, entities, or taxonomy term references), and map to RDF as best you can (I'm sure there'll be discussions, we can talk it out using this issue).

After configuring the metadata profile for the 'Repository Item' content type, export its field and field storage definitions into the `islandora_demo_feature` feature.  You'll also want to re-export the RDF mapping with any changes you've made.

**Comment by rosiel** [comment]
We're using the sandbox described in https://groups.google.com/forum/#!topic/islandora/Me8J0aXhjjw to build something up. I had created a bunch of vocabularies, then exported the config, before a vagrant destroy. 

For three vocabularies, I imported the following files:

`core.entity_form_display.taxonomy_term.dcmi_type_vocabulary.default.yml
core.entity_form_display.taxonomy_term.iana_mime_types.default.yml
core.entity_form_display.taxonomy_term.lcsh_library_of_congress_subject.default.yml
core.entity_form_display.taxonomy_term.marc_resource_types_scheme.default.yml
core.entity_view_display.taxonomy_term.dcmi_type_vocabulary.default.yml
core.entity_view_display.taxonomy_term.iana_mime_types.default.yml
core.entity_view_display.taxonomy_term.lcsh_library_of_congress_subject.default.yml
core.entity_view_display.taxonomy_term.marc_resource_types_scheme.default.yml
field.field.taxonomy_term.dcmi_type_vocabulary.field_comment.yml
field.field.taxonomy_term.dcmi_type_vocabulary.field_externally_managed_uri.yml
field.field.taxonomy_term.dcmi_type_vocabulary.field_vocabulary_encoding_scheme.yml
field.field.taxonomy_term.iana_mime_types.field_vocabulary_encoding_scheme.yml
field.field.taxonomy_term.lcsh_library_of_congress_subject.field_externally_managed_uri.yml
field.field.taxonomy_term.lcsh_library_of_congress_subject.field_vocabulary_encoding_scheme.yml
field.field.taxonomy_term.marc_resource_types_scheme.field_externally_managed_uri.yml
field.storage.taxonomy_term.field_comment.yml
field.storage.taxonomy_term.field_external_uri.yml
field.storage.taxonomy_term.field_externally_managed_uri.yml
field.storage.taxonomy_term.field_vocabulary_encoding_scheme.yml
taxonomy.vocabulary.dcmi_type_vocabulary.yml
taxonomy.vocabulary.iana_mime_types.yml
taxonomy.vocabulary.lcsh_library_of_congress_subject.yml
taxonomy.vocabulary.marc_resource_types_scheme.yml`

And that doesn't even attach them to the repository object... or fill the vocabs with values. 

I have some csv's of values to go in to these, scraping or cherry-picking from existing vocabularies. Not sure what to do with them...

**Comment by seth-shaw-unlv** [comment]
@rosiel 

1) do you have a copy of those config files you can share? Or is there a PR forthcoming?

2) It looks like you have subjects and types as taxonomy terms are all implemented as taxonomy terms. The existing controlled_access_terms implements subjects as normal content types. Should we update it to use the fields you describe here?

**Comment by rtilla1** [comment]
I believe I have added the small number of field names in Drupal and mapped them to the correct Typein that sandbox. @rosiel had already added the few that are controlled/reconcile, and I didn't touch those. If we are able to give you a list of LCSH (with or without their URIs), or some other list that would need to be included in one of the taxonomies above, can someone spend some time tomorrow morning showing us how to import a CSV to those? Also, how to import a CSV of metadata objects into CLAW/what format the CSV should be in?

**Comment by seth-shaw-unlv** [comment]
Oh! I didn't see the sandbox there. Okay.

So, to import a CSV of taxonomy terms we need to define a migration config. We can talk about it during tomorrow's "XML2CSV to Islandora CLAW" call. If you want to send me a CSV I can prep for it.

**Comment by rtilla1** [comment]
I believe I have added the small number of field names in Drupal and mapped them to the correct Typein that sandbox. @rosiel had already added the few that are controlled/reconcile, and I didn't touch those. If we are able to give you a list of LCSH (with or without their URIs), or some other list that would need to be included in one of the taxonomies above, can someone spend some time tomorrow morning showing us how to import a CSV to those? Also, how to import a CSV of metadata objects into CLAW/what format the CSV should be in?

**Comment by seth-shaw-unlv** [comment]
@rtilla1 It doesn't really matter what structure the CSV is, since you can update the migration to match.  For terms, all you really need is the LCSH term. You don't even really need a CSV. 

For example, I have a [proof-of-concept module](https://github.com/seth-shaw-unlv/claw-migrate-files-poc) that defines a new content model and configures a migration based on some [MADS RDFXML records](https://github.com/seth-shaw-unlv/claw-migrate-files-poc/blob/master/data/apollo-auths.rdf) and a [CSV of object records](https://github.com/seth-shaw-unlv/claw-migrate-files-poc/blob/master/data/apollo.csv). One of those migrations [looks for all the Topic records](https://github.com/seth-shaw-unlv/claw-migrate-files-poc/blob/master/migrate_apollo/config/install/migrate_plus.migration.auth_topic.yml#L10) and [creates "subject" nodes](https://github.com/seth-shaw-unlv/claw-migrate-files-poc/blob/master/migrate_apollo/config/install/migrate_plus.migration.auth_topic.yml#L33-41). The [image metadata objects are migrated from a CSV](https://github.com/seth-shaw-unlv/claw-migrate-files-poc/blob/master/migrate_apollo/config/install/migrate_plus.migration.claw_image.yml). The [columns of the CSV are defined as part of the source section](https://github.com/seth-shaw-unlv/claw-migrate-files-poc/blob/master/migrate_apollo/config/install/migrate_plus.migration.claw_image.yml#L24-L34) and [their mappings as part of the process section](https://github.com/seth-shaw-unlv/claw-migrate-files-poc/blob/master/migrate_apollo/config/install/migrate_plus.migration.claw_image.yml#L39-L114). This example uses the [term value to look up the subject node](https://github.com/seth-shaw-unlv/claw-migrate-files-poc/blob/master/migrate_apollo/config/install/migrate_plus.migration.claw_image.yml#L99-L105), but it could be changed to use the URI fairly easily if that is what you have.

_I may come back and plop some of the code bits directly into this comment later._

**Comment by seth-shaw-unlv** [comment]
@rosiel and @rtilla1, on the Sandbox we have two taxonomies for types (MARC types and DCMI types) with separate repository object fields for each. How would you feel about the following changes?

1. Create a single type field that allows values from either/both taxonomies?
2. Allow multiple types to be selected?
3. Create a single taxonomy containing both types?

**Comment by seth-shaw-unlv** [comment]
Based on the [migration sprint wrap-up call](https://github.com/Islandora-CLAW/CLAW/wiki/CLAW-Migration-Sprint-Wrap-Up-Meeting), it looks like Yes to the first two and "maybe" for the last one. We will have to try it out. Also, @whikloj suggested using a view for the auto-complete to support disambiguation. We'll see how it goes.

**Comment by seth-shaw-unlv** [comment]
In case anyone is interested, the current WIP branch I'm using is @ https://github.com/seth-shaw-unlv/islandora_demo/tree/issue-896. 

I think it is almost ready for a PR, although it requires PR https://github.com/Islandora-CLAW/controlled_access_terms/pull/8.

**Comment by Natkeeran** [comment]
@seth-shaw-unlv Can you please push this as PR.  I can test this.

**Comment by seth-shaw-unlv** [comment]
@Natkeeran see https://github.com/Islandora-CLAW/islandora_demo/pull/2

**Comment by seth-shaw-unlv** [comment]
@Natkeeran "cloning a content type (Say Repository Item - MODS, Repository Item - DC)" is what we were planning to do here (although probably dropping the "Repository Item - " prefix).

**Comment by dannylamb** [comment]
@seth-shaw-unlv feel free to close this.  If we have improvements to the default metadata profile to make, we'll do separate issues.
