### ISSUE TITLE
Create GenerateVideoDerivative Action

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#956]
Like https://github.com/Islandora-CLAW/islandora_image, we need a module that supplies an action to trigger video derivatives.  Create a new module `islandora_video`, and put in a plugin: `src/Plugin/ContextReaction/GenerateVideoDerivative.php`.  Look to https://github.com/Islandora-CLAW/islandora_image/blob/8.x-1.x/src/Plugin/Action/GenerateImageDerivative.php for guidance.  There's likely a lot of overlap in code, so feel free to abstract into a base class in the core `islandora` for better re-use.

**Comment by whikloj** [comment]
This is all based off of the #888 PRs so I won't even open PRs until that is merged, because I'll probably have to rebase then.

islandora - https://github.com/dannylamb/islandora/compare/issue-888...whikloj:issue-956
islandora_demo - https://github.com/dannylamb/islandora_demo/compare/issue-888...whikloj:issue-956

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-CLAW/islandora/commit/4ba1816ed91fcb5f7ab77b56145496fc63332248 and https://github.com/Islandora-CLAW/islandora_demo/commit/03884c56561576a6c951a846cd3ec34e306f3fd3
