### ISSUE TITLE
Migrating versions of MODS datastreams

### ISSUE THREAD

**Issue by mjordan** [Islandora-CLAW/CLAW#959]
I was going to frame this as a use case issue, but perhaps it premature to do that. If anyone has a use case for migrating versions of their MODS datastreams, we can create a structure use case and go from there.

Based on an IRC conversation between @dannylamb, @whikloj, and myself, it appears that migrating just the current version of MODS metadata is an order of magnitude simpler than migrating all versions of the MODS datastream. We thought it would be good to confirm that the communitiy's expectations were that only the current MODS values would be migrated before closing the door, for now, on migrating all versions.

The reason migrating only the current version of metadata values is much simpler is that we can get those values directly from the MODS datastream (or even from the indexed values in Solr as @DiegoPino has suggested) and not have to worry about migrating (or managing) the previous versions.

So, this is an open invitation for the community to articulate use cases for migrating versions of metadata values other than the most recent versions. Has anyone ever had to revert versions of their MODS metadata, and if so, did you do it on multiple objects? We'd love to hear from people in the Metadata IG and others with an opinion on this question.

**Comment by dannylamb** [comment]
@mjordan I brought this up at the most recent MIG meeting and consensus was it's not a big deal to ignore historical versions of metadata like this.  Most of the MIG is going to do open refine and then import from a CSV, so they'd lose the history on descriptive MD as well.  If coming from FOXML, the assumption is that versions would be edits, and you want the most recent version because that will have the most correct metadata.  However, the MIG brought up that it would be good to ask the IR interest group too.

So... @bryjbrown 

Does this sort of thing matter to the IR interest group?  If we pulled your descriptive metadata out from Solr instead of from the XML directly, would that be a barrier to migrating from 7.x to CLAW?

**Comment by mjordan** [comment]
@dannylamb @bryjbrown can we close this?

**Comment by dannylamb** [comment]
Closing.  @bryjbrown (or anyone) can re-open if they feel the need.  I've asked around in meetings, too, and have yet to find someone with the use case for migrating older versions of descriptive md.  The latest is always the most correct and is what should be used.
