### ISSUE TITLE
Remove port mapping to "Islandora Microservices"

### ISSUE THREAD

**Issue by mjordan** [Islandora-CLAW/CLAW#989]
Microservices run on port 8000, not 8282. Can we remove https://github.com/Islandora-Devops/claw-playbook/blob/master/Vagrantfile#L39?

**Comment by dannylamb** [comment]
YES

**Comment by mjordan** [comment]
And according to `claw-playbook/roles/external/Islandora-Devops.karaf/tasks/service.yml`, Karaf runs on port 8101, not 8181 as stated in the Vagrantfile. Fix that in the same PR?

**Comment by mjordan** [comment]
Or remove it?

**Comment by dannylamb** [comment]
I think 8181 would be if you were running hawt.io or something like that to monitor your karaf, but it's been absolutely ages since I've done something like that.    You can also SSH into it, which may be what 8101 is, but again, I haven't messed with that stuff in forever.

It's probably just best to remove it.

**Comment by mjordan** [comment]
OK, will open a PR later today.

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-Devops/claw-playbook/commit/d0f9539080a86ea0fcf13127bcf3e09c4703e5a5
