### ISSUE TITLE
Add tests for the `EntityBundle` and `JsonldAlterTypeReaction` plugins

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#992]
Follow up to https://github.com/Islandora-CLAW/islandora/pull/107

See https://github.com/Islandora-CLAW/islandora/blob/8.x-1.x/tests/src/Functional/ContentEntityTypeTest.php for `EntityBundle` and https://github.com/Islandora-CLAW/islandora/blob/8.x-1.x/tests/src/Functional/MappingUriPredicateReactionTest.php for `JsonldAlterTypeReaction`.

You should be able to copy/paste your way through with those.  Ping me if you have any questions

**Comment by seth-shaw-unlv** [comment]
🎶I see what is happening here.... you're face to face with _Contexts_ and it's strange...🎶

I had written the EntityBundle condition under the assumption that the user was getting the resource (it's initial use case was as part of the jsonld normalize array). However, the test case from ContentEntityType works on the creation of a node, which meant my strategy of getting the node from context based on a passed parameter broke. The simple solution was to modify the condition's evaluate function to more robustly identify the appropriate context to retrieve the entity in question. 

Now I just need to make sure it does actually still work for the original purpose like I think it should.

**Comment by seth-shaw-unlv** [comment]
I have the EntityBundleTest working fine.

What I've been banging my head against is the JsonldTypeAlterReactionTest. For the test I need to add a text field to the test content type (test_type) we make in IslandoraFunctionalTestBase. All the examples I've seen to do this use the FieldUiTestTrait. [I tried to use it](https://github.com/seth-shaw-unlv/islandora/blob/91bd2a15f424f7c59073755643b2b838e21dcc13/tests/src/Functional/JsonldTypeAlterReactionTest.php#L26) but it is broken with the dev version of Mink that Drupal installs. The trait passes a translatable string to the assertion rather than a string, which is fine for the stable version of Mink which used preg_match, but breaks with dev version of Mink (as of January 2018) which now uses stripos. So, once I can figure out how to create this field without the trait, or force a stable Mink version, I can move forward with this...

**Comment by seth-shaw-unlv** [comment]
Decided to simply copy over the parts of FieldUiTestTrait that were needed; just a few lines. Now the PR is up.

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-CLAW/islandora/commit/57070658accb9e0cf553ece64d28e03891ba9f3a
